[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"
# don't run `cargo update`: Dependabot updates dependencies, and the `licenses` CI job
# fails on any dependency version not in THIRDPARTY.yml
dependencies_update = false
# labels for the release PR
pr_labels = ["release"]
# disable git releases (handled by publish workflow)
git_release_enable = false
# disable running `cargo-semver-checks` until after the first release
semver_check = false
