//! Raw FFI bindings to NCBI's `libncbi-vdb` C library.
//!
//! This crate provides low-level, unsafe bindings generated by `bindgen`.
//! Users should prefer the safe wrappers in the `fg-sra-vdb` crate.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
